export default {
  HTTPBASEURL: process.env.HTTPBASEURL,
  HTTPOPENAPIURL: process.env.HTTPOPENAPIURL,
  HTTPHEADER_APPID: '100006',
  HTTPHEADER_APPVERSION: '',
  HTTPHEADER_APPSIGN: 'SONGCHE',
  PAGE_SIZE: process.env.PAGE_SIZE
};
